apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.selector.app }}
  name: {{ .Values.deployment.name }}
  namespace: microservices
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app }}
    spec:
      containers:
        - image: {{ .Values.deployment.image.name }}
          name: {{ .Values.deployment.name }}
          ports:
            - containerPort: {{ .Values.deployment.ports.containerPort }}
              protocol: {{ .Values.deployment.ports.protocol }}
