apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.17.2
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    server: https://152.70.103.225:6443
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
