apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.25.0
      helm:
        valueFiles:
          - $values/charts/istio/istiod/values.yaml
    - repoURL: https://github.com/yoshikanes/helm-chart.git
      targetRevision: main
      ref: values
  destination:
    server: https://152.70.103.225:6443
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true