apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yoshikanes/helm-chart.git
    targetRevision: main
    path: charts/apps/kafka-api
    helm:
      valueFiles:
        - values/dev.yaml
  destination:
    server: https://152.70.103.225:6443
    namespace: microservices
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
        pod-security.kubernetes.io/enforce: privileged
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
