resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
cni:
  enabled: true
istiodRemote:
  enabled: true
  injectionURL: "https://158.179.183.148:15017/inject/cluster/cluster2/net/network1"
  injectionCABundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvVENDQWVXZ0F3SUJBZ0lSQUxpdHVCZlVXUjRZTjJIM0E0TmJpZG93RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU5UQTJNVEl3TWpVMk1qVmFGdzB6TlRBMgpNVEF3TWpVMk1qVmFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRG5Lc2dQVnUzL2Z0QTYxUkxMVVAyV0IvN3JiNkVzNHlEY1RJWmgKUUpxNkFPZ2FnOFM0a1JJa28yMnpoRmxVelVxdE1iR0U0dXBrZ1E4UXpxa2M3c2dYM1UwclN4emlrREtyTHNiWgpCVlY0cTN5a1FzclptRi9aKzdXUCtSWXI3c0NOaDJoQi9mMUIxaTZqWWNaT2s2dnk4WWlneEdWN2ZRMC83Q2dRClRweDhkcS8xSXh4RnFoa0d0RDRqOHdkRU1ycmM5bXA0ZldVOHUwMEcxZzIzK0tPMi9XcVZiWWJ0YXB6N2FxMW8KTUhUSjFMZ2VadHRqZU1ybXRNNkdOaXNjSTE0VW0zSXVwd0M2a0FVMU42RXU0Z09NVTJCQk92ZGYrMnlucHRQLwoyZXI4SWRCSlg2S3MrWEJZVzZ4Q3dRcVVkaTEwSTBva0o2UDRjUVZwZjBCbjhQR0xBZ01CQUFHalFqQkFNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlFGTHk3aTNYK0wKNUtiVVZRTm94dUJieWRydG5EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFONmZTbzkwVnM1M05qM1NzaXhpdwoyK2gwanYybWUrSHdOZDYxUU1RWDNwZEhIYlZiVnY0Q2dHcncybTVYcXo4NkVZMlJTYXYySFFZRnQ3RnJ6SVEwCjVra3dtb3EzdDNFNSt0RDRGUENUcFQ3NXZHNkh1MTd4RHJIWko3NHlwcDRYejNUaER3Qk9UYXRqbEd2TmhMKy8KQ0VnQnlra3I1cHJGMHg4MU9tbDhsejlQQm90aUtXSXFiWGNLYWhBaU1tNmsrd0swYXhBZkF0YjhkUVFIVUtlWQpHVTVBSWFvMlIrdWVqbXIrWGd3Z01oODN6OERpbmtJc2JMVGl5ZGRCYjRvcnJ5Ym9QUDd1V2Y5bEc0NG10TGVwCjE1R2JFYW1lTkYrQXk2cmxpQmlEWUNtbysrcGxaczQwR21XUnJVVHV3UjdrTVA1QXg2b2MwTHZWRWpQNm9JZUQKV1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
global:
  proxy:
    logLevel: debug
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
  proxy_init:
    image: proxyv2
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
  remotePilotAddress: "158.179.183.148"
  externalIstiod: true 
  meshID: "mesh1"
  multiCluster:
    enabled: true
    clusterName: "cluster2"
  network: "network1"
  waypoint:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi