resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
cni:
  enabled: true
istiodRemote:
  enabled: true
  injectionURL: "https://158.179.183.148:15017/inject/cluster/cluster2/net/network1"
  injectionCABundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpVENDQW5HZ0F3SUJBZ0lSQU5BTm1JNUNSMGQyNHlVZjlkR3pBZGd3RFFZSktvWklodmNOQVFFTEJRQXcKWGpFUE1BMEdBMVVFQXd3R1N6aHpJRU5CTVFzd0NRWURWUVFHRXdKVlV6RVBNQTBHQTFVRUJ3d0dRWFZ6ZEdsdQpNUTh3RFFZRFZRUUtEQVpQY21GamJHVXhEREFLQmdOVkJBc01BMDlqYVRFT01Bd0dBMVVFQ0F3RlZHVjRZWE13CkhoY05NalV3TWpFM01EWTBORFUyV2hjTk16QXdNakUzTURZME5EVTJXakJlTVE4d0RRWURWUVFEREFaTE9ITWcKUTBFeEN6QUpCZ05WQkFZVEFsVlRNUTh3RFFZRFZRUUhEQVpCZFhOMGFXNHhEekFOQmdOVkJBb01Cazl5WVdOcwpaVEVNTUFvR0ExVUVDd3dEVDJOcE1RNHdEQVlEVlFRSURBVlVaWGhoY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5SNGExdytTbzhEL2l5NXNkVVkwa3Fna1lNUmhEM3k1Q2hwZC9GeGI5KzUKbWViY3BydndBazR2Zk9oNmFnRmNDR3RjSDFhS0FWTE55ZmVrOEIzS09VanptNzBleS9FTXdqaUdHMlh0TGFqMgorQ2kvNWxKemw1VzBQb21oRU1tODhvZEQzbzhNZGRCelZBVmZ2QTQxbVo0M3ZDSU03K044eU5KWXlMcEdEKzgwCnhWcFhHcUJ1aXRjeXNZeVc0TVVtREpJWFVUUWVsdVI3ZzFHVHRxN0F0ZDVkVHhxRHdObUZ5VlJYUG1ZazJBQisKcnNlYmhLdFZGVndoWUNqZ2JIb1FkRjk0QkV6R0k0Q0FiT0NuK2UxLy9vMGxQQ2dySmt3b2pyMGpXNE9hWU1RZgpnRndqL0xTMlFra3BqTllFdlhwMlYvWGo3SnRsT2xNYm9CT1QwQUFTbjNFQ0F3RUFBYU5DTUVBd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVFZd0hRWURWUjBPQkJZRUZQL2hSYm9keFE2MjRHM1MKK2hSQkNyUmd5YlcxTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCb1dXL01OZWtEM2xoVklZK1pOWEpieFJWcQpFcmtoaUhZajROMng4RTlDTHpzOTNYUU1venBqUlN4YXcyT3B3ZWVhSkJqdDFNbWRDRXdCRVNZNmtYYmVVS3I3CnM0Y0Q2Vms1ZVhSbTZRMFhPZWVzTHkybUJZMXJrSUMrbWhPbEI5bFBaV0E2YU42bFJ1SzAzSThxTVlkWGIzSVcKREpBdklYL2xEcEovYlgxVVc5MGxkN2xwMC9XdTVMYjQvZUtJeWxjN0V6UDR6dCsrSWFmZHZPRm4rOVZWTHhzNgpLRzdvUDZXcXBiTjBzcnBXZzZ1WUtEQllzWGxPeGpPWHQ1TWxZVUQzVWIra1U0WnhnR3JieFlhREZEaSttNnRFCnBOOGVqSzkwaHdicmtwakF4VDduTE53b01Vd1hjYVBFQWdrQ0NlLzJNZmZFd3NjYjhDU0tlei9xZVVYYQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
global:
  proxy:
    logLevel: debug
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
  proxy_init:
    image: proxyv2
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
  remotePilotAddress: "158.179.183.148"
  externalIstiod: true 
  meshID: "mesh1"
  multiCluster:
    enabled: true
    clusterName: "cluster2"
  configCluster: true
  network: "network1"
  waypoint:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
