resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
cni:
  enabled: true
global:
  proxy:
    logLevel: debug
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
  proxy_init:
    image: proxyv2
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
  waypoint:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
  meshID: "mesh1"
  multiCluster:
    enabled: true
    clusterName: "cluster1"
  network: "network1"