alertmanager:
  enabled: false
grafana:
  ingress:
    enabled: true
    ingressClassName: native-ic-ingress-class
    annotations:
      oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
      oci-native-ingress.oraclecloud.com/healthcheck-port: "3000"
      oci-native-ingress.oraclecloud.com/healthcheck-path: "/api/health"
      oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeia7kgvokkxpmee6s6v2opcur6jah223vk6b34z5dyhqrqq"
      oci-native-ingress.oraclecloud.com/backend-tls-enabled: "false"
      oci-native-ingress.oraclecloud.com/https-listener-port: "443"
    hosts:
      - grafana.dev.ec-gaihan-development.com
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.logging.svc.cluster.local:3100
      version: 1
      isDefault: false
      jsonData:
        maxLines: 1000
      editable: false
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: development
    thanos:
      image: quay.io/thanos/thanos:v0.38.0
      version: v0.38.0
      objectStorageConfig:
        secret:
          type: OCI
          config:
            provider: "instance-principal"
            bucket: "thanos-metrics-storage"
            compartment_ocid: "ocid1.compartment.oc1..aaaaaaaagmkqp2efcynmjicfgucpd4b3i6mzurw3ndfjy7my7qajy32dmhkq"
  thanosService:
    enabled: true
