deployment:
    name: kafka-ui
    replicaCount: 1
    env:
        clustersBootstrapServers: kafka-service:9092
        clustersName: local
    image:
        name: provectuslabs/kafka-ui
        tag: latest
    ports:
        containerPort: 8080
        protocol: TCP
service:
    name: kafka-ui
    ports:
        port: 80
        targetPort: 8080
selector:
    app: kafka-ui
ingress:
    name: kafka-ingress
    annotations:
        healthCheckProtocol: "HTTP"
        healthCheckPort: "8080"
        healthCheckPath: "/"
        certificateOCID: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeia7kgvokkxpmee6s6v2opcur6jah223vk6b34z5dyhqrqq"
        backendTLSEnabled: "false"
        httpsListenerPort: "443"
    ingressClassName: native-ic-ingress-class
    rules:
        hostName: kafka.dev.ec-gaihan-development.com
        path: /
        pathType: Prefix