deployment:
    name: rabbitmq
    replicaCount: 1
    env:
        defaultPass: pass
        defaultUser: user
    image:
        name: rabbitmq
        tag: 4.1.0-beta.5-management
    ports:
        mainContainerPort: 15672
        subContainerPort: 5672
        protocol: TCP
service:
    name: rabbitmq
    ports:
        mainPortName: main
        mainPort: 80
        mainTargetPort: 15672
        subPortName: sub
        subPort: 5672
        subTargetPort: 5672
selector:
    app: rabbitmq
ingress:
    name: rabbitmq-ingress
    annotations:
        healthCheckProtocol: "HTTP"
        healthCheckPort: "15672"
        healthCheckPath: "/"
        certificateOCID: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeia7kgvokkxpmee6s6v2opcur6jah223vk6b34z5dyhqrqq"
        backendTLSEnabled: "false"
        httpsListenerPort: "443"
    ingressClassName: native-ic-ingress-class
    rules:
        hostName: rabbitmq.dev.ec-gaihan-development.com
        path: /
        pathType: Prefix