
additional_display_details:
- annotation: kiali.io/api-spec
  icon_annotation: kiali.io/api-type
  title: API Documentation

istio_namespace: "istio-system" # default is where Kiali is installed

auth:
  strategy: "anonymous"

clustering:
  autodetect_secrets:
    enabled: false
    label: "kiali.io/multiCluster=false"

deployment:
  additional_service_yaml: {}
  # The Kiali server helm chart only supports cluster-wide access; setting cluster_wide_access to false is not supported.
  # For more control over what the Kial Service Account can see, use the Kiali Operator.
  cluster_wide_access: true
  image_digest: "" # use "sha256" if image_version is a sha256 hash (do NOT prefix this value with a "@")
  image_name: quay.io/kiali/kiali
  image_pull_policy: "Always"
  image_version: v2.5.0 # version like "v1.39" (see: https://quay.io/repository/kiali/kiali?tab=tags) or a digest hash
  ingress:
    enabled: true
    additional_labels: {}
    ingressClassName: "native-ic-ingress-class"
    override_yaml:
      metadata:
        annotations:
          oci-native-ingress.oraclecloud.com/backend-tls-enabled: "false"
          oci-native-ingress.oraclecloud.com/backend-protocol: "HTTP"
              # ★注意: このOCIDはKialiのホスト名に対応する証明書のOCIDに置き換えてください
          oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeiavxd6vjvcxgbypmq23qeqxztqpwyw6ihuk5n6f4yer4ua"
          oci-native-ingress.oraclecloud.com/https-listener-port: "443"
      spec:
        rules:
        - host: kiali.mgmt.ec-gaihan-development.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: kiali
                    port:
                      number: 20001
  # if deployment.hpa is defined, this replicas setting will be ignored
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      memory: "1Gi"
  secret_name: "kiali"
  service_type: "ClusterIP"
  version_label: v2.5.0 # v1.39 # v1.39.0 # see: https://quay.io/repository/kiali/kiali?tab=tags
  view_only_mode: false

external_services:
  prometheus:
    enabled: true
    url: "http://thanos-query.monitoring.svc.cluster.local:9090"
  istio:
    root_namespace: "istio-system"

server:
  port: 20001
  #node_port:
  observability:
    metrics:
      enabled: true
      port: 9090
  web_root: ""