allowAllAccessibleNamespaces: true

cr:
  create: true   # これがUI起動の鍵です
  name: kiali
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    deployment:
      ingress:
        enabled: true
        class_name: "native-ic-ingress-class" # ingressClassNameの代わり
        override_yaml:
          metadata:
            annotations:
              oci-native-ingress.oraclecloud.com/secure-backends: "false"
              oci-native-ingress.oraclecloud.com/backend-protocol: "HTTP"
              # ★注意: このOCIDはKialiのホスト名に対応する証明書のOCIDに置き換えてください
              oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeiavxd6vjvcxgbypmq23qeqxztqpwyw6ihuk5n6f4yer4ua"
              cluster_wide_access: "true"
        host: kiali.mgmt.ec-gaihan-development.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: "kiali"
                port:
                  number: 20001

  external_services:
    prometheus:
      url: "http://thanos-query.monitoring.svc.cluster.local:9090"
  istio_namespace: ""


  deployment_view:
    enabled: true

  istio_component_namespaces:
    prometheus: monitoring
