allowAllAccessibleNamespaces: true

cr:
  create: true   # これがUI起動の鍵です
  name: kiali
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    deployment:
      ingress:
        enabled: true
        class_name: "native-ic-ingress-class" # ingressClassNameの代わり
        annotations:
          override_yaml:
            metadata:
              annotations:
                oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
                oci-native-ingress.oraclecloud.com/healthcheck-path: "/"
                # ★注意: このOCIDはKialiのホスト名に対応する証明書のOCIDに置き換えてください
                oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa_YOUR_KIALI_CERT_OCID"      
      cluster_wide_access: true
    server:
      web_fqdn: "kiali.mgmt.ec-gaihan-development.com"

    external_services:
      prometheus:
        url: "http://thanos-query.monitoring.svc.cluster.local:9090"
    istio_namespace: ""