# この内容をArgo CDのvaluesに設定してください。
# Argo CDのApplicationマニフェストの spec.source.helm.values に直接記述するか、
# この内容でvalues.yamlファイルを作成して参照させます。

# 'kiali:' というキーで、IstioチャートにKialiサブチャート用の設定を渡します
kiali:
  # Kialiコンポーネントを有効化します
  enabled: true

  # Kialiダッシュボードの設定
  dashboard:
    # 外部サービスとしてPrometheusを指定します
    # (ご提示のファイルにあった追記点3に相当します)
    # ※お使いのIstioのバージョンによってはキー名が異なる可能性があります
    external_services:
      prometheus:
        # ご自身の環境のPrometheusのURL
        url: "http://dev-kube-prometheus-stack-prometheus.monitoring:9090"

  # Kialiが監視する名前空間を指定します
  deployment:
    accessible_namespaces:
      - "**"
