# この内容をArgo CDのvaluesに設定してください。
# Argo CDのApplicationマニフェストの spec.source.helm.values に直接記述するか、
# この内容でvalues.yamlファイルを作成して参照させます。

# 'kiali:' というキーで、IstioチャートにKialiサブチャート用の設定を渡します
kiali:
  deployment:
    namespace: istio-system
  ingress:
    enabled: true

  # Kialiダッシュボードの設定
  dashboard:
    # 外部サービスとしてPrometheusを指定します
    # (ご提示のファイルにあった追記点3に相当します)
    # ※お使いのIstioのバージョンによってはキー名が異なる可能性があります


  # Kialiが監視する名前空間を指定します
  deployment:
    accessible_namespaces:
      - "microservices"
cr:
  create: true   # これがUI起動の鍵です
  name: kiali
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    deployment:
      cluster_wide_access: true
    server:
      web_fqdn: "kiali.dev.ec-gaihan-development.com"
    external_services:
      prometheus:
        # ご自身の環境のPrometheusのURL
        url: "http://istio-prometheus-server.istio-system.svc.cluster.local:80"