kiali:
  deployment:
    namespace: istio-system
  ingress:
    enabled: true
    hosts:
      - "istio.dev.ec-gaihan-development.com"
    annotations:
      oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
      oci-native-ingress.oraclecloud.com/healthcheck-port: "20001"
      oci-native-ingress.oraclecloud.com/healthcheck-path: "/kiali/healthz"
      oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeiavxd6vjvcxgbypmq23qeqxztqpwyw6ihuk5n6f4yer4ua"
      oci-native-ingress.oraclecloud.com/backend-tls-enabled: "false"
      oci-native-ingress.oraclecloud.com/https-listener-port: "443"
    ingressClassName: native-ic-ingress-class
  route:
    enabled: false

cr:
  create: true   # これがUI起動の鍵です
  name: kiali
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    deployment:
      cluster_wide_access: true
    server:
      web_fqdn: "istio.dev.ec-gaihan-development.com"