image: pilot
traceSampling: 1.0
resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "150m"
    memory: "128Mi"
cni:
  enabled: true
  provider: default
keepaliveMaxServerConnectionAge: 30m
configMap: true
sidecarInjectorWebhook:
  enableNamespacesByDefault: false
  reinvocationPolicy: Never
  rewriteAppHTTPProbe: true
istiodRemote:
  enabled: false
telemetry:
  enabled: true
  v2:
    enabled: true
    prometheus:
      enabled: true
    stackdriver:
      enabled: false
meshConfig:
  enablePrometheusMerge: true
experimental:
  stableValidationPolicy: false
global:
  istioNamespace: istio-system
  defaultPodDisruptionBudget:
    enabled: true
  defaultResources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
  hub: docker.io/istio
  tag: 1.26.0
  istiod:
    enableAnalysis: false
  logAsJson: false
  logging:
    level: "default:info"
  omitSidecarInjectorConfigMap: false
  operatorManageWebhooks: false
  proxy:
    image: proxyv2
    autoInject: enabled
    clusterDomain: "cluster.local"
    componentLogLevel: "misc:error"
    excludeInboundPorts: ""
    includeInboundPorts: "*"
    includeIPRanges: "*"
    excludeIPRanges: ""
    includeOutboundPorts: "*"
    excludeOutboundPorts: ""
    # Log level for proxy, applies to gateways and sidecars.
    # Expected values are: trace|debug|info|warning|error|critical|off
    logLevel: debug
    outlierLogPath: ""
    privileged: false
    readinessFailureThreshold: 4
    readinessInitialDelaySeconds: 0
    readinessPeriodSeconds: 15
    startupProbe:
      enabled: true
      failureThreshold: 600 # 10 minutes
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "150m"
        memory: "128Mi"
    statusPort: 15020
    tracer: "none"
  proxy_init:
    image: proxyv2
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "150m"
        memory: "128Mi"
    forceApplyIptables: false
  externalIstiod: false
  meshID: "mesh1"
  multiCluster:
    enabled: true
    clusterName: "cluster1"
  network: "network1"
  waypoint:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
base:
  enableIstioConfigCRDs: true