_internal_defaults_do_not_set:
  profile: "remote"
  image: pilot
  traceSampling: 1.0
  resources:
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"
  # Whether to use an existing CNI installation
  cni:
    enabled: true
    provider: default

  keepaliveMaxServerConnectionAge: 30m
  configMap: true


  sidecarInjectorWebhook:
    injectedAnnotations: {}
    enableNamespacesByDefault: false
    reinvocationPolicy: Never
    rewriteAppHTTPProbe: true

  istiodRemote:
    enabled: true
    injectionURL: "https://10.96.195.116:15017/inject/cluster/cluster2/net/network1"
    #injectionPath: "/inject/cluster/cluster2/net/network1"
    injectionCABundle: ""
  telemetry:
    enabled: true
    v2:
      enabled: true
      prometheus:
        enabled: true
      stackdriver:
        enabled: false
  revision: ""
  revisionTags: []
  meshConfig:
    enablePrometheusMerge: true
  experimental:
    stableValidationPolicy: false

  global:
    istioNamespace: istio-system
    certSigners: []
    defaultPodDisruptionBudget:
      enabled: true
    defaultResources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
    hub: docker.io/istio
    tag: 1.26.0
    variant: ""
    imagePullPolicy: ""
    imagePullSecrets: []
    istiod:
      enableAnalysis: false
    logAsJson: false
    logging:
      level: "default:info"

    omitSidecarInjectorConfigMap: false
    operatorManageWebhooks: false
    proxy:
      image: proxyv2
      autoInject: enabled
      clusterDomain: "cluster.local"
      componentLogLevel: "misc:error"
      excludeInboundPorts: ""
      includeInboundPorts: "*"
      includeIPRanges: "*"
      excludeIPRanges: ""
      includeOutboundPorts: ""
      excludeOutboundPorts: ""

      # Log level for proxy, applies to gateways and sidecars.
      # Expected values are: trace|debug|info|warning|error|critical|off
      logLevel: warning
      outlierLogPath: ""
      privileged: false
      readinessFailureThreshold: 4
      readinessInitialDelaySeconds: 0
      readinessPeriodSeconds: 15
      startupProbe:
        enabled: true
        failureThreshold: 600 # 10 minutes
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "150m"
          memory: "128Mi"
      statusPort: 15020.
      tracer: "none"

    proxy_init:
      image: proxyv2
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "150m"
          memory: "128Mi"
      forceApplyIptables: false

    remotePilotAddress: "158.179.183.148"
    caAddress: ""
    externalIstiod: true
    configCluster: true
  
    meshID: "mesh1"
    multiCluster:
      enabled: true
      clusterName: "cluster2"
    network: "network1"
    waypoint:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 150m
          memory: 128Mi
  base:
    enableIstioConfigCRDs: true

