server:
  ingress:
    enabled: true
    annotations:
      oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
      oci-native-ingress.oraclecloud.com/healthcheck-port: "8080"
      oci-native-ingress.oraclecloud.com/healthcheck-path: "/"
    ingressClassName: native-ic-ingress-class
    hostname: argocd.mgmt.ec-gaihan-development.com
    extraRules:
      - http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80