compartment_id: "ocid1.compartment.oc1..aaaaaaaat34dbqqstzlkz4apgguqhnvna5crdcgenkd4hsjjl3cdtr7wl5fq"
subnet_id: "ocid1.subnet.oc1.ap-tokyo-1.aaaaaaaad72zzofvywqzrnrtstembgwbzwvufinvkx3shndv5c43narzpudq"
cluster_id: "ocid1.cluster.oc1.ap-tokyo-1.aaaaaaaa3xm2cwq2clksukvbf35fkxoz4mhhok3xnenwzbtgqcwnqw52ysxa"