_internal_defaults_do_not_set:  
  image: install-cni
  logging:
    level: "debug"

  cniBinDir: /opt/cni/bin
  cniConfDir: /etc/cni/net.d
  cniConfFileName: ""
  cniNetnsDir: "/var/run/netns"

  excludeNamespaces:
    - kube-system
  chained: true
  provider: "default"
  ambient:
    enabled: false
    dnsCapture: false
  repair:
    enabled: true
    labelPods: false
    deletePods: false
    repairPods: true
    initContainerName: "istio-validation"
    brokenPodLabelKey: "cni.istio.io/uninitialized"
    brokenPodLabelValue: "true"

  global:
    hub: docker.io/istio
    tag: 1.26.1
    logging:
      level: info
    logAsJson: false