# Argo CDのvaluesとして使用するYAML
cni:
  hub: ""
  tag: ""
  variant: ""
  image: install-cni
  pullPolicy: ""
  logLevel: debug
  cniConfDir: /etc/cni/net.d
  cniConfFileName: ""
  cniBinDir: ""
  cniNetnsDir: "" # Defaults to '/var/run/netns', in minikube/docker/others can be '/var/run/docker/netns'.
  excludeNamespaces:
    - kube-system
  affinity: {}
  podAnnotations: {}
  chained: true
  provider: "default"
  ambient:
    enabled: false
    configDir: ""
    dnsCapture: false
  repair:
    enabled: true
    hub: ""
    tag: ""
    labelPods: false
    deletePods: false
    repairPods: true
    initContainerName: "istio-validation"
    brokenPodLabelKey: "cni.istio.io/uninitialized"
    brokenPodLabelValue: "true"
  seccompProfile: {}
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  resourceQuotas:
    enabled: false
    pods: 5000
  rollingMaxUnavailable: 1

revision: ""
ownerName: ""

global:
  hub: docker.io/istio
  tag: 1.22.1
  variant: ""
  imagePullPolicy: ""
  logging:
    level: default:info,cni:info
  logAsJson: false
  imagePullSecrets: []
  # - private-registry-key
  defaultResources:
    requests:
      cpu: 100m
      memory: 100Mi