apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.selector.app }}
  name: {{ .Values.service.name }}
  namespace: microservices
spec:
  ports:
    - port: {{ .Values.service.ports.subPort }}
      targetPort: {{ .Values.service.ports.subTargetPort }}
    - port: {{ .Values.service.ports.mainPort }}
      targetPort: {{ .Values.service.ports.mainTargetPort }}
  selector:
    app: {{ .Values.selector.app }}
