auth:
  strategy: "anonymous"
deployment:
  ingress:
    enabled: true
    class_name: "native-ic-ingress-class"
    override_yaml:
      metadata:
        annotations:
          oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
          oci-native-ingress.oraclecloud.com/backend-tls-enabled: "false"
          oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeiavxd6vjvcxgbypmq23qeqxztqpwyw6ihuk5n6f4yer4ua"
          oci-native-ingress.oraclecloud.com/https-listener-port: "443"
      spec:
        rules:
        - host: kiali.mgmt.ec-gaihan-development.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: kiali
                    port:
                      number: 20001
        kubernetes_config:
          cluster_name: cluster1
  resources:
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"

external_services:
  prometheus:
    enabled: true
    url: "http://thanos-query.thanos.svc.cluster.local:9090"
