apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-mgmt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.17.2
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: featureGates
          value: "ExperimentalCertificateSigningRequestControllers=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
