apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller-mgmt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oracle/oci-native-ingress-controller.git
    targetRevision: v1.4.2
    path: helm/oci-native-ingress-controller
    helm:
      releaseName: oci-native-ingress-controller
      values: |
        compartment_id: "ocid1.compartment.oc1..aaaaaaaagmkqp2efcynmjicfgucpd4b3i6mzurw3ndfjy7my7qajy32dmhkq"
        subnet_id: "ocid1.subnet.oc1.ap-tokyo-1.aaaaaaaaslh3ctk4zlrlcvdoqm3gppvrtntr5jbdmsf4dvwsomcld2zerppq"
  destination:
    server: https://kubernetes.default.svc
    namespace: native-ingress-controller-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
