apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-mgmt
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.22.1
      helm:
        valueFiles:
          - $values/charts/istio/eastwestgateway/values.yaml
    - repoURL: https://github.com/yoshikanes/helm-chart.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true