apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/yoshikanes/helm-chart.git
    targetRevision: main
    path: charts/apps/zookeeper
    helm:
      valueFiles:
        - values/dev.yaml
  destination:
    server: https://152.70.103.225:6443
    namespace: microservices
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
