apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-mgmt
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-server
      targetRevision: 2.10.0
      helm:
        valueFiles:
          - $values/values/external/kiali/values.yaml
    - repoURL: https://github.com/yoshikanes/helm-chart.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true