deployment:
    name: kafka-api
    replicaCount: 1
    env:
        appPort: 8001
        bootstrapServers: kafka-service:9092
    image:
        name: nrt.ocir.io/nrcmxxv7sjse/ec_service_test:kafka-api-v5
    ports:
        containerPort: 8001
        protocol: TCP
service:
    name: kafka-api
    ports:
        port: 80
        targetPort: 8001
selector:
    app: kafka-api
ingress:
    name: kafka-api-ingress
    annotations:
        healthCheckProtocol: "HTTP"
        healthCheckPort: "8001"
        healthCheckPath: "/"
        certificateOCID: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeia7kgvokkxpmee6s6v2opcur6jah223vk6b34z5dyhqrqq"
        backendTLSEnabled: "false"
        httpsListenerPort: "443"
    ingressClassName: native-ic-ingress-class
    rules:
        hostName: kafka-api.dev.ec-gaihan-development.com
        path: /
        pathType: Prefix