apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yoshikanes/helm-chart.git
    targetRevision: main
    path: charts/applications/microservice-db
    helm:
      valueFiles:
        - ../../../values/internal/microservice-db/values-dev.yaml
  destination:
    server: https://152.70.103.225:6443
    namespace: microservices
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
