apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.selector.app }}
  name: {{ .Values.service.name }}
  namespace: microservices
spec:
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: {{ .Values.selector.app }}
