deployment:
    name: graphql-service
    replicaCount: 1
    image:
        name: nrt.ocir.io/nrcmxxv7sjse/ec_service_test:graphql-service
    ports:
        containerPort: 80
        protocol: TCP
service:
    name: graphql-service
    ports:
        port: 80
        targetPort: 80
selector:
    app: graphql-service