apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: mgmt
            url: https://kubernetes.default.svc
          - cluster: dev
            url: https://152.70.103.225:6443
  template:
    metadata:
      name: '{{cluster}}-cert-manager'
    spec:
      project: default
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: 1.17.2
        helm:
          parameters:
            - name: installCRDs
              value: "true"
      destination:
        server: '{{url}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
