apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  generators:
    - list:
        elements:
          - cluster: mgmt
            url: https://kubernetes.default.svc
          - cluster: dev
            url: https://152.70.103.225:6443
  template:
    metadata:
      name: '{{cluster}}-istio-istiod'
    spec:
      project: default
      sources:
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: istiod
          targetRevision: 1.26.0
          helm:
            valueFiles:
              - $values/charts/istio/istiod/values-{{cluster}}.yaml
        - repoURL: https://github.com/yoshikanes/helm-chart.git
          targetRevision: main
          ref: values
      destination:
        server: '{{url}}'
        namespace: istio-system
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: validation.istio.io
          jsonPointers:
            - /webhooks/0/failurePolicy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
