apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.selector.app }}
  name: {{ .Values.persistentvolumeclaim.name }}
  namespace: microservices
spec:
  accessModes:
    - {{ .Values.persistentvolumeclaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentvolumeclaim.resources.storage }}
