secret:
  jwt:
    anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
    serviceKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
    secret: 2e6ef68c02b7b8df1242625cdd36265b692329a31d968d82b1326be7a8b49043
  smtp:
    username: your-mail@example.com
    password: example123456
  dashboard:
    username: admin
    password: supabasepass
  db:
    username: admin
    password: zG96uXB#
    database: postgres
  analytics:
    apiKey: be334195618a822311835f10fc353d3844a98563e39c18a2102be70e1ad1e9cd

db:
  enabled: false #外部DBを使用する場合はfalseにする
  # image:
  #   tag: 15.1.0.147
  # livenessProbe:
  #   exec:
  #     command:
  #       - pg_isready
  #       - -U
  #       - postgres
  #   initialDelaySeconds: 3
  # persistence:
  #   enabled: false #本番環境ではtrueにする

studio:
  image:
    tag: 20240326-5e5586d
  environment:
    STUDIO_DEFAULT_ORGANIZATION: "EC Gaihan"
    STUDIO_DEFAULT_PROJECT: "Test Project"
    SUPABASE_PUBLIC_URL: https://supabase.dev.ec-gaihan-development.com/
    NEXT_PUBLIC_ENABLE_LOGS: "true"
  livenessProbe:
    httpGet:
      path: /api/profile
      port: 3000
    initialDelaySeconds: 3

auth:
  image:
    tag: v2.143.0
  environment:
    DB_HOST: "primary.z7rgd7dbag4mxf52n2fykieftmgreq.postgresql.ap-tokyo-1.oci.oraclecloud.com"
    DB_USER: "admin"
    DB_SSL: "require"
    API_EXTERNAL_URL: https://supabase.dev.ec-gaihan-development.com/
    GOTRUE_SITE_URL: https://supabase.dev.ec-gaihan-development.com/
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
    GOTRUE_SMTP_HOST: "smtp.example.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"

rest:
  image:
    tag: v12.0.1
  environment:
    DB_HOST: "primary.z7rgd7dbag4mxf52n2fykieftmgreq.postgresql.ap-tokyo-1.oci.oraclecloud.com"
    DB_USER: "admin"
    DB_SSL: "require"

realtime:
  image:
    tag: v2.34.47
  livenessProbe:
    httpGet:
      path: /
      port: 4000
    initialDelaySeconds: 3
  environment:
    DB_HOST: "primary.z7rgd7dbag4mxf52n2fykieftmgreq.postgresql.ap-tokyo-1.oci.oraclecloud.com"
    DB_USER: "admin"
    DB_SSL: "require"
    DB_PORT: "5432"
    APP_NAME: "realtime"
    SEED_SELF_HOST: "true"

meta:
  image:
    tag: v0.80.0
  environment:
    DB_HOST: "primary.z7rgd7dbag4mxf52n2fykieftmgreq.postgresql.ap-tokyo-1.oci.oraclecloud.com"
    DB_USER: "admin"
    DB_SSL: "require"

storage:
  image:
    tag: v0.46.4
  livenessProbe:
    httpGet:
      path: /status
      port: 5000
    initialDelaySeconds: 3
  persistence:
    enabled: false #本番環境ではtrueにする
  environment:
    DB_HOST: "primary.z7rgd7dbag4mxf52n2fykieftmgreq.postgresql.ap-tokyo-1.oci.oraclecloud.com"
    DB_USER: "admin"
    DB_SSL: "require"
    PGSSLMODE: "require"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"

imgproxy:
  image:
    tag: v3.8.0
  environment:
    IMGPROXY_ENABLE_WEBP_DETECTION: "true"
  livenessProbe:
    exec:
      command:
        - imgproxy
        - health
    initialDelaySeconds: 3
  persistence:
    enabled: false

kong:
  image:
    repository: kong
    tag: 2.8.1
  environment:
    KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
    KONG_LOG_LEVEL: info
  ingress:
    enabled: true
    className: "native-ic-ingress-class"
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: null
        # oci-native-ingress.oraclecloud.com/healthcheck-protocol: "HTTP"
        # oci-native-ingress.oraclecloud.com/healthcheck-port: "3000"
        # oci-native-ingress.oraclecloud.com/healthcheck-path: "/api/profile"
        oci-native-ingress.oraclecloud.com/certificate-ocid: "ocid1.certificate.oc1.ap-tokyo-1.amaaaaaa5plvdeia7kgvokkxpmee6s6v2opcur6jah223vk6b34z5dyhqrqq"
        oci-native-ingress.oraclecloud.com/backend-tls-enabled: "false"
        oci-native-ingress.oraclecloud.com/https-listener-port: "443"
    hosts:
      - host: supabase.dev.ec-gaihan-development.com
        paths:
          - path: /
            pathType: Prefix

analytics:
  enabled: false #外部DBでは使用出来ないようなので無効化
  # image:
  #   tag: 1.4.0
  # livenessProbe:
  #   httpGet:
  #     path: /health
  #     port: 4000
  #   initialDelaySeconds: 3
  # environment:
  #   DB_HOST: "primary.z7rgd7dbag4mxf52n2fykieftmgreq.postgresql.ap-tokyo-1.oci.oraclecloud.com"
  #   DB_USERNAME: "admin"

vector:
  enabled: false #analyticsに依存しているため無効化
  # image:
  #   tag: 0.34.0-alpine
  # livenessProbe:
  #   httpGet:
  #     path: /health
  #     port: 9001
  #   initialDelaySeconds: 3
  # volumeMounts:
  #   - name: pod-logs
  #     mountPath: /var/log/pods
  # volumes:
  #   - name: pod-logs
  #     hostPath:
  #       path: /var/log/pods

functions:
  image:
    tag: v1.41.2
  environment:
    DB_HOST: "primary.z7rgd7dbag4mxf52n2fykieftmgreq.postgresql.ap-tokyo-1.oci.oraclecloud.com"
    DB_USER: "admin"
    DB_SSL: "require"