apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .dev.selector.app }}
  name: {{ .dev.service.name }}
  namespace: microservices
spec:
  ports:
    - protocol: {{ .dev.service.ports.protocol }}
      port: {{ .dev.service.ports.port }}
      targetPort: {{ .dev.service.ports.targetPort }}
  selector:
    app: {{ .dev.selector.app }}