apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-controller
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: mgmt
            url: https://kubernetes.default.svc
          - cluster: dev
            url: https://152.70.103.225:6443
  template:
    metadata:
      name: '{{cluster}}-ingress-controller'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/oracle/oci-native-ingress-controller.git
          targetRevision: v1.4.2
          path: helm/oci-native-ingress-controller
          helm:
            releaseName: oci-native-ingress-controller
            valueFiles:
              - $values/values/external/oci-native-ingress-controller/values-{{cluster}}.yaml
        - repoURL: https://github.com/yoshikanes/helm-chart.git
          targetRevision: main
          ref: values
      destination:
        server: '{{url}}'
        namespace: native-ingress-controller-system
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
